services:
  db:
    image: postgres:13
    container_name: getpet_db
    environment:
      POSTGRES_USER: getpet
      POSTGRES_PASSWORD: getpet
      POSTGRES_DB: getpet
    networks:
      - app-network
  api:
    build:
      context: ./getpet
    container_name: getpet_api
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: getpet
      DATABASE_PASSWORD: getpet
      DATABASE_NAME: getpet
    networks:
      - app-network
    depends_on:
      - db

  frontend:
      build:
        context: ./front-facilita_ai
        dockerfile: Dockerfile
      container_name: getpet_front
      volumes:
        - ./front-facilita_ai:/usr/src/app
        - /usr/src/app/node_modules
      environment:
        - VITE_API_URL=/api
      networks:
        - app-network
      depends_on:
        - api

  nginx:
    image: nginx:alpine
    container_name: getpet_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - api
      - frontend

networks:
  app-network:
    driver: bridge
